### ISSUE TITLE
Adicionar uma licença open source <3 [duplicado]

### ISSUE THREAD

**Issue by mauriciomelo** [peixebabel/simple-recognition#12]

**Comment by nullhack** [comment]
Já há uma issue aberta para isso: issue https://github.com/peixebabel/simple-recognition/issues/4

Inclusive já fiz um pull request nesse sentido, utilizando a licença MIT: https://github.com/peixebabel/simple-recognition/pull/9

Se quiser ajude a bombar a issue para que ela comece um quadro focando software livre no canal: A issue https://github.com/peixebabel/simple-recognition/issues/11

**Comment by mauriciomelo** [comment]
Legal @nullhack, estou fechando essa issue já que está duplicada com a #4

**Comment by dunossauro** [comment]
Galera, tem que ser GPL, MIT não. Pensa em novos projetos virando sofware proprietario?

Não vai dar muito certo.

**Comment by nullhack** [comment]
@z4r4tu5tr4 Entendo seu ponto, foi uma das sugestões que fiz na issue https://github.com/peixebabel/simple-recognition/issues/4 . Porém fiz um pull request da MIT pois não sei qual a intenção da Camila em relação a esse projeto (ela não se pronunciou desde a criação do repositório) por isso deixei a licença mais aberta possível. Além disso, mesmo que evolua bastante, não vejo como sendo um projeto comercialmente viável, além disso, não sei como ficam licenças em relação às imagens de pokémon usando uma licença viral como a GPL. Não sou advogado, mas acho que isso pode dar algum problema.

O que podemos fazer nesse meio tempo é discutir sobre licenças, até um pronunciamento oficial.

A princípio, não vejo como problema fazer um fork privado e fechar o código, pois, até onde entendi, a ideia de liberar o código é exemplificar conceitos expostos nos vídeos... não vejo uma concorrência comercial surgindo a partir disso, e a MIT mantém o direito da Camila criar distribuições fechadas a partir de seu próprio código. Caso alguém colabore e a licença seja GPL, até onde eu entendo, ela teria que conseguir autorização explícita de todos os colaboradores para fazer isso (e não sei o quanto isso poderia atrapalhar o projeto de mestrado dela).

Particularmente prefiro a GPL também. Mas como o projeto não é meu e não sei o nível de envolvimento dela com liberdade de software, mantive a sugestão do MIT como sendo melhor do que o estado atual (atualmente o código está sem uma licença de uso livre) e sem envolver questões mais profundas de filosofia de software.

Além disso, a MIT é extremamente simples de ler e entender. Vejo essa como a principal vantagem em relação à GPL, que infelizmente é muito grande e complexa (apesar de poder ser resumida em 4 linhas, toda a parte de resguardo do autor e viralidade do código adicionam complexidade).
